# Generated by Django 3.2.19 on 2023-07-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0005_auto_20230722_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
