# Generated by Django 3.2.19 on 2023-08-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0006_alter_assignment_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
