# Generated by Django 3.2.19 on 2023-08-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0007_qcstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='qc_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project_id',
            field=models.IntegerField(),
        ),
    ]
