# Generated by Django 3.2.20 on 2023-08-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0008_auto_20230823_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcstatus',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
    ]
