# Generated by Django 3.2.19 on 2023-09-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0009_qcstatus_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100, null=True)),
                ('project_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
