# Generated by Django 3.2.19 on 2023-09-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0010_folderprojectmapping_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
