# Generated by Django 3.2.19 on 2023-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0011_assignment_assigned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_id', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
