<<<<<<< HEAD
# Generated by Django 3.2.20 on 2023-10-30 11:17
=======
# Generated by Django 3.2.20 on 2023-09-14 05:40
>>>>>>> 63c35fe5952e26fe79feac3cf6f0b022ce500c7c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0012_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcstatus',
            name='reason',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
