info = {"message": "docs: Add release notes for 2.4.9-5 (#4628)", "commit": "c7d886068a0641d7c6507a42be659003db375eb9", "date": "2023/08/11 22:42:08", "branch": "develop", "version": "1.4.1+1448.gc7d88606.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
